<?php
include('class_inmueble.php');
include("class_Db.php");

class inmueble_dal extends class_Db
{
    public function __construct()
    {
        parent::__construct();
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    //Checa si existe la matricula en la tabla especiales, retorna un int
    /*function existe_matricula_especiales($matr)
    {
        $matr = $this->db_conn->real_escape_string($matr);

        $this->set_sql(
            "SELECT * FROM especiales WHERE matricula = '$matr'"
        );

        $rs = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $total_rs = mysqli_num_rows($rs);

        return $total_rs;
    }*/

    function insertar($obj){
		$sql = "insert into inmueble (encabezado,descripcion,direccion,costo_inmueble,recamaras,baños,estacionamientos,estatus,ciudad,estado,codigo_postal,area_terreno,email,latitud,longitud,exterior,interior_1,interior_2) ";
		$sql .= "values(";
        $sql .= "'".$obj->getEncabezado()."',";
    	$sql .= "'".$obj->getDescripcion()."',";
        $sql .= "'".$obj->getDireccion()."',";
        $sql .= "'".$obj->getCosto_inmueble()."',";
        $sql .= "'".$obj->getRecamaras()."',";
        $sql .= "'".$obj->getBaños()."', ";
        $sql .= "'".$obj->getEstacionamientos()."', ";
        $sql .= "'".$obj->getEstatus()."', ";
        $sql .= "'".$obj->getCiudad()."', ";
        $sql .= "'".$obj->getEstado()."', ";
        $sql .= "'".$obj->getCodigo_postal()."', ";
        $sql .= "'".$obj->getArea_terreno()."', ";
        $sql .= "'".$obj->getEmail()."', ";
        $sql .= "'".$obj->getLatitud()."', ";
        $sql .= "'".$obj->getLongitud()."', ";
        $sql .= "'".$obj->getExterior()."', ";
        $sql .= "'".$obj->getInterior_1()."', ";
        $sql .= "'".$obj->getInterior_2()."'";
        $sql .= ")";
		//print $sql;exit;
	   	$this->set_sql($sql);
        $this->db_conn->set_charset("utf8");
    	mysqli_query($this->db_conn,$this->db_query) or die(mysqli_error($this->db_conn));
        if(mysqli_affected_rows($this->db_conn)==1) {
			$insertado=1;
			//print "insertado"."\n";
		}else{
			$insertado=0;
		}
		unset($obj);
 		return $insertado;
  	}

    function eliminar($id_inmueble){
        $sql = "DELETE FROM inmueble WHERE id_inmueble = '$id_inmueble'";
        $this->set_sql($sql);
        $this->db_conn->set_charset("utf8");
        $resultado = mysqli_query($this->db_conn,$this->db_query) or die(mysqli_error($this->db_conn));
        return $resultado;
    }

    function actualizar($id_inmueble, $encabezado, $descripcion, $costo_inmueble, $email){
        $sql = "UPDATE inmueble SET encabezado='$encabezado', descripcion='$descripcion', costo_inmueble='$costo_inmueble', email='$email' WHERE id_inmueble = '$id_inmueble'";
        $this->set_sql($sql);
        $this->db_conn->set_charset("utf8");
        $resultado = mysqli_query($this->db_conn,$this->db_query) or die(mysqli_error($this->db_conn));
        return $resultado;
    }



    //Trae los datos de la tabla inmuebles'
    /*function get_datos_inmuebles()
    {
        $this->set_sql(
            "SELECT encabezado, direccion, costo_inmueble, recamaras, baños, estacionamientos, ciudad, estado, area_terreno, estatus FROM inmueble 
                    FROM inmueble"
        );

        $rs = mysqli_query($this->db_conn, $this->db_query) or die(mysqli_error($this->db_conn));
        $row = mysqli_fetch_assoc($rs);

        $obj = new inmueble();
        $obj->setEncabezado(utf8_encode($row['encabezado']));
        $obj->setDireccion(utf8_encode($row['direccion']));
        $obj->setCosto_inmueble($row['costo_inmueble']);
        $obj->setRecamaras($row['recamaras']);
        $obj->setBaños($row['baños']);
        $obj->setEstacionamientos($row['estacionamientos']);
        $obj->setCiudad(utf8_encode($row['ciudad']));
        $obj->setEstado(utf8_encode($row['estado']));
        $obj->setArea_terreno($row['area_terreno']);
        $obj->setEstatus(utf8_encode($row['estatus']));

        return $resultado;
    }*/
}
